on: 
  push:
    branches: 
      - hexo-source
name: Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: hexo-source
      - name: Install dependency
        run: npm install
      - name: Clean
        uses: heowc/action-hexo@master
        with:
          args: clean
      - name: Generate
        uses: heowc/action-hexo@master
        with:
          args: generate
      - name: Hexo GitHub Action
        uses: yrpang/github-actions-hexo@v1.1
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          username: kbyyd24
          email: melo@gaoyuexiang.cn
          github_token: ${{secrets.GITHUB_TOKEN}}
