on: 
  push:
    branches: 
      - hexo-source
name: Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: hexo-source
      - name: Build and Deploy
        uses: yrpang/github-actions-hexo@master
        with:
          deployKey: ${{ secrets.DEPLOY_KEY }}
          username: kbyyd24_blog_publisher
          email: melo@gaoyuexiang.cn
