on: 
  push:
    branches: 
      - hexo-source
name: Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          ref: hexo-source
      - name: Build and Deploy
        uses: Forest10/hexo-deploy-action-with-cname@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REPOSITORY: kbyyd24/kbyyd24.github.io
          BRANCH: master
          PUBLISH_DIR: ./public
